USE dmef;

DROP TABLE IF EXISTS `extra_junio_1`;

CREATE TABLE `extra_junio_1` (
numero_de_cliente INT DEFAULT NULL,

cuenta_estados INT DEFAULT NULL,

cliente_edad__cliente_antiguedad DECIMAL(7,5) DEFAULT NULL,
cliente_edad__Visa_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
cliente_edad__Master_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
cliente_edad__Visa_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
cliente_edad__Master_mlimitecompra DECIMAL(7,5) DEFAULT NULL,

Master_madelantodolares__Master_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Master_madelantopesos__Master_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Master_marca_atraso__Master_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Master_mconsumosdolares__Master_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Master_mconsumospesos__Master_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Master_mconsumototal__Master_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Master_mlimitecompra__Master_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Master_mpagado__Master_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Master_mpagominimo__Master_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Master_mpagosdolares__Master_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Master_mpagospesos__Master_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Master_msaldodolares__Master_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Master_msaldopesos__Master_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Master_msaldototal__Master_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Master_tadelantosefectivo__Master_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Master_tconsumos__Master_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,

Master_madelantodolares__Master_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Master_madelantopesos__Master_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Master_marca_atraso__Master_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Master_mconsumosdolares__Master_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Master_mconsumospesos__Master_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Master_mconsumototal__Master_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Master_mfinanciacion_limite__Master_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Master_mpagado__Master_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Master_mpagominimo__Master_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Master_mpagosdolares__Master_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Master_mpagospesos__Master_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Master_msaldodolares__Master_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Master_msaldopesos__Master_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Master_msaldototal__Master_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Master_tadelantosefectivo__Master_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Master_tconsumos__Master_mlimitecompra DECIMAL(7,5) DEFAULT NULL,

Visa_madelantodolares__Visa_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Visa_madelantopesos__Visa_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Visa_marca_atraso__Visa_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Visa_mconsumosdolares__Visa_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Visa_mconsumospesos__Visa_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Visa_mconsumototal__Visa_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Visa_mlimitecompra__Visa_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Visa_mpagado__Visa_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Visa_mpagominimo__Visa_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Visa_mpagosdolares__Visa_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Visa_mpagospesos__Visa_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Visa_msaldodolares__Visa_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Visa_msaldopesos__Visa_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Visa_msaldototal__Visa_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Visa_tadelantosefectivo__Visa_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,
Visa_tconsumos__Visa_mfinanciacion_limite DECIMAL(7,5) DEFAULT NULL,

Visa_madelantodolares__Visa_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Visa_madelantopesos__Visa_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Visa_marca_atraso__Visa_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Visa_mconsumosdolares__Visa_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Visa_mconsumospesos__Visa_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Visa_mconsumototal__Visa_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Visa_mfinanciacion_limite__Visa_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Visa_mpagado__Visa_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Visa_mpagominimo__Visa_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Visa_mpagosdolares__Visa_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Visa_mpagospesos__Visa_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Visa_msaldodolares__Visa_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Visa_msaldopesos__Visa_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Visa_msaldototal__Visa_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Visa_tadelantosefectivo__Visa_mlimitecompra DECIMAL(7,5) DEFAULT NULL,
Visa_tconsumos__Visa_mlimitecompra DECIMAL(7,5) DEFAULT NULL
);

ALTER TABLE `extra_junio_1` ADD INDEX `numero_de_cliente_idx` (`numero_de_cliente`);
