TRUNCATE extra_abril_4;

INSERT INTO extra_abril_4 (
numero_de_cliente,

mactivos_margen__Master_mfl,
marketing_coss_selling__Master_mfl,
mautoservicio__Master_mfl,
mbonos_corporativos__Master_mfl,
mcaja_ahorro_Nopaquete__Master_mfl,
mcaja_ahorro_Paquete__Master_mfl,
mcaja_ahorro_dolares__Master_mfl,
mcajeros_ajenos__Master_mfl,
mcajeros_propio__Master_mfl,
mcajeros_propios_descuentos__Master_mfl,
mcambio_monedas_compra__Master_mfl,
mcambio_monedas_venta__Master_mfl,
mcheques_depositados__Master_mfl,
mcheques_depositados_rechazados__Master_mfl,
mcheques_emitidos__Master_mfl,
mcheques_emitidos_rechazados__Master_mfl,
mcomisiones__Master_mfl,
mcomisiones_mantenimiento__Master_mfl,
mcomisiones_otras__Master_mfl,
mcuenta_corriente_Nopaquete__Master_mfl,
mcuenta_corriente_Paquete__Master_mfl,
mcuenta_corriente_dolares__Master_mfl,
mcuenta_debitos_automaticos__Master_mfl,
mcuenta_descuentos__Master_mfl,
mcuentas_saldo__Master_mfl,
mdescubierto_preacordado__Master_mfl,
mextraccion_autoservicio__Master_mfl,
mfondos_comunes_inversion_dolares__Master_mfl,
mfondos_comunes_inversion_pesos__Master_mfl,
minversiones_otras__Master_mfl,
mmonedas_extranjeras__Master_mfl,
mpagodeservicios__Master_mfl,
mpagomiscuentas__Master_mfl,
mpasivos_margen__Master_mfl,
mprestamos_hipotecarios__Master_mfl,
mprestamos_personales__Master_mfl,
mprestamos_prendarios__Master_mfl,
mrentabilidad__Master_mfl,
mrentabilidad_annual__Master_mfl,
mtarjeta_master_consumo__Master_mfl,
mtarjeta_master_descuentos__Master_mfl,
mtarjeta_visa_consumo__Master_mfl,
mtarjeta_visa_descuentos__Master_mfl,
mtitulos__Master_mfl,
mtransferencias_emitidas__Master_mfl,
mtransferencias_recibidas__Master_mfl,
mttarjeta_master_debitos_automaticos__Master_mfl,
mttarjeta_visa_debitos_automaticos__Master_mfl,

mactivos_margen__Visa_mfl,
marketing_coss_selling__Visa_mfl,
mautoservicio__Visa_mfl,
mbonos_corporativos__Visa_mfl,
mcaja_ahorro_Nopaquete__Visa_mfl,
mcaja_ahorro_Paquete__Visa_mfl,
mcaja_ahorro_dolares__Visa_mfl,
mcajeros_ajenos__Visa_mfl,
mcajeros_propio__Visa_mfl,
mcajeros_propios_descuentos__Visa_mfl,
mcambio_monedas_compra__Visa_mfl,
mcambio_monedas_venta__Visa_mfl,
mcheques_depositados__Visa_mfl,
mcheques_depositados_rechazados__Visa_mfl,
mcheques_emitidos__Visa_mfl,
mcheques_emitidos_rechazados__Visa_mfl,
mcomisiones__Visa_mfl,
mcomisiones_mantenimiento__Visa_mfl,
mcomisiones_otras__Visa_mfl,
mcuenta_corriente_Nopaquete__Visa_mfl,
mcuenta_corriente_Paquete__Visa_mfl,
mcuenta_corriente_dolares__Visa_mfl,
mcuenta_debitos_automaticos__Visa_mfl,
mcuenta_descuentos__Visa_mfl,
mcuentas_saldo__Visa_mfl,
mdescubierto_preacordado__Visa_mfl,
mextraccion_autoservicio__Visa_mfl,
mfondos_comunes_inversion_dolares__Visa_mfl,
mfondos_comunes_inversion_pesos__Visa_mfl,
minversiones_otras__Visa_mfl,
mmonedas_extranjeras__Visa_mfl,
mpagodeservicios__Visa_mfl,
mpagomiscuentas__Visa_mfl,
mpasivos_margen__Visa_mfl,
mprestamos_hipotecarios__Visa_mfl,
mprestamos_personales__Visa_mfl,
mprestamos_prendarios__Visa_mfl,
mrentabilidad__Visa_mfl,
mrentabilidad_annual__Visa_mfl,
mtarjeta_master_consumo__Visa_mfl,
mtarjeta_master_descuentos__Visa_mfl,
mtarjeta_visa_consumo__Visa_mfl,
mtarjeta_visa_descuentos__Visa_mfl,
mtitulos__Visa_mfl,
mtransferencias_emitidas__Visa_mfl,
mtransferencias_recibidas__Visa_mfl,
mttarjeta_master_debitos_automaticos__Visa_mfl,
mttarjeta_visa_debitos_automaticos__Visa_mfl,

mactivos_margen__Master_mlc,
marketing_coss_selling__Master_mlc,
mautoservicio__Master_mlc,
mbonos_corporativos__Master_mlc,
mcaja_ahorro_Nopaquete__Master_mlc,
mcaja_ahorro_Paquete__Master_mlc,
mcaja_ahorro_dolares__Master_mlc,
mcajeros_ajenos__Master_mlc,
mcajeros_propio__Master_mlc,
mcajeros_propios_descuentos__Master_mlc,
mcambio_monedas_compra__Master_mlc,
mcambio_monedas_venta__Master_mlc,
mcheques_depositados__Master_mlc,
mcheques_depositados_rechazados__Master_mlc,
mcheques_emitidos__Master_mlc,
mcheques_emitidos_rechazados__Master_mlc,
mcomisiones__Master_mlc,
mcomisiones_mantenimiento__Master_mlc,
mcomisiones_otras__Master_mlc,
mcuenta_corriente_Nopaquete__Master_mlc,
mcuenta_corriente_Paquete__Master_mlc,
mcuenta_corriente_dolares__Master_mlc,
mcuenta_debitos_automaticos__Master_mlc,
mcuenta_descuentos__Master_mlc,
mcuentas_saldo__Master_mlc,
mdescubierto_preacordado__Master_mlc,
mextraccion_autoservicio__Master_mlc,
mfondos_comunes_inversion_dolares__Master_mlc,
mfondos_comunes_inversion_pesos__Master_mlc,
minversiones_otras__Master_mlc,
mmonedas_extranjeras__Master_mlc,
mpagodeservicios__Master_mlc,
mpagomiscuentas__Master_mlc,
mpasivos_margen__Master_mlc,
mprestamos_hipotecarios__Master_mlc,
mprestamos_personales__Master_mlc,
mprestamos_prendarios__Master_mlc,
mrentabilidad__Master_mlc,
mrentabilidad_annual__Master_mlc,
mtarjeta_master_consumo__Master_mlc,
mtarjeta_master_descuentos__Master_mlc,
mtarjeta_visa_consumo__Master_mlc,
mtarjeta_visa_descuentos__Master_mlc,
mtitulos__Master_mlc,
mtransferencias_emitidas__Master_mlc,
mtransferencias_recibidas__Master_mlc,
mttarjeta_master_debitos_automaticos__Master_mlc,
mttarjeta_visa_debitos_automaticos__Master_mlc,

mactivos_margen__Visa_mlc,
marketing_coss_selling__Visa_mlc,
mautoservicio__Visa_mlc,
mbonos_corporativos__Visa_mlc,
mcaja_ahorro_Nopaquete__Visa_mlc,
mcaja_ahorro_Paquete__Visa_mlc,
mcaja_ahorro_dolares__Visa_mlc,
mcajeros_ajenos__Visa_mlc,
mcajeros_propio__Visa_mlc,
mcajeros_propios_descuentos__Visa_mlc,
mcambio_monedas_compra__Visa_mlc,
mcambio_monedas_venta__Visa_mlc,
mcheques_depositados__Visa_mlc,
mcheques_depositados_rechazados__Visa_mlc,
mcheques_emitidos__Visa_mlc,
mcheques_emitidos_rechazados__Visa_mlc,
mcomisiones__Visa_mlc,
mcomisiones_mantenimiento__Visa_mlc,
mcomisiones_otras__Visa_mlc,
mcuenta_corriente_Nopaquete__Visa_mlc,
mcuenta_corriente_Paquete__Visa_mlc,
mcuenta_corriente_dolares__Visa_mlc,
mcuenta_debitos_automaticos__Visa_mlc,
mcuenta_descuentos__Visa_mlc,
mcuentas_saldo__Visa_mlc,
mdescubierto_preacordado__Visa_mlc,
mextraccion_autoservicio__Visa_mlc,
mfondos_comunes_inversion_dolares__Visa_mlc,
mfondos_comunes_inversion_pesos__Visa_mlc,
minversiones_otras__Visa_mlc,
mmonedas_extranjeras__Visa_mlc,
mpagodeservicios__Visa_mlc,
mpagomiscuentas__Visa_mlc,
mpasivos_margen__Visa_mlc,
mprestamos_hipotecarios__Visa_mlc,
mprestamos_personales__Visa_mlc,
mprestamos_prendarios__Visa_mlc,
mrentabilidad__Visa_mlc,
mrentabilidad_annual__Visa_mlc,
mtarjeta_master_consumo__Visa_mlc,
mtarjeta_master_descuentos__Visa_mlc,
mtarjeta_visa_consumo__Visa_mlc,
mtarjeta_visa_descuentos__Visa_mlc,
mtitulos__Visa_mlc,
mtransferencias_emitidas__Visa_mlc,
mtransferencias_recibidas__Visa_mlc,
mttarjeta_master_debitos_automaticos__Visa_mlc,
mttarjeta_visa_debitos_automaticos__Visa_mlc,

mactivos_margen__VisaMaster_mfl,
marketing_coss_selling__VisaMaster_mfl,
mautoservicio__VisaMaster_mfl,
mbonos_corporativos__VisaMaster_mfl,
mcaja_ahorro_Nopaquete__VisaMaster_mfl,
mcaja_ahorro_Paquete__VisaMaster_mfl,
mcaja_ahorro_dolares__VisaMaster_mfl,
mcajeros_ajenos__VisaMaster_mfl,
mcajeros_propio__VisaMaster_mfl,
mcajeros_propios_descuentos__VisaMaster_mfl,
mcambio_monedas_compra__VisaMaster_mfl,
mcambio_monedas_venta__VisaMaster_mfl,
mcheques_depositados__VisaMaster_mfl,
mcheques_depositados_rechazados__VisaMaster_mfl,
mcheques_emitidos__VisaMaster_mfl,
mcheques_emitidos_rechazados__VisaMaster_mfl,
mcomisiones__VisaMaster_mfl,
mcomisiones_mantenimiento__VisaMaster_mfl,
mcomisiones_otras__VisaMaster_mfl,
mcuenta_corriente_Nopaquete__VisaMaster_mfl,
mcuenta_corriente_Paquete__VisaMaster_mfl,
mcuenta_corriente_dolares__VisaMaster_mfl,
mcuenta_debitos_automaticos__VisaMaster_mfl,
mcuenta_descuentos__VisaMaster_mfl,
mcuentas_saldo__VisaMaster_mfl,
mdescubierto_preacordado__VisaMaster_mfl,
mextraccion_autoservicio__VisaMaster_mfl,
mfondos_comunes_inversion_dolares__VisaMaster_mfl,
mfondos_comunes_inversion_pesos__VisaMaster_mfl,
minversiones_otras__VisaMaster_mfl,
mmonedas_extranjeras__VisaMaster_mfl,
mpagodeservicios__VisaMaster_mfl,
mpagomiscuentas__VisaMaster_mfl,
mpasivos_margen__VisaMaster_mfl,
mprestamos_hipotecarios__VisaMaster_mfl,
mprestamos_personales__VisaMaster_mfl,
mprestamos_prendarios__VisaMaster_mfl,
mrentabilidad__VisaMaster_mfl,
mrentabilidad_annual__VisaMaster_mfl,
mtarjeta_master_consumo__VisaMaster_mfl,
mtarjeta_master_descuentos__VisaMaster_mfl,
mtarjeta_visa_consumo__VisaMaster_mfl,
mtarjeta_visa_descuentos__VisaMaster_mfl,
mtitulos__VisaMaster_mfl,
mtransferencias_emitidas__VisaMaster_mfl,
mtransferencias_recibidas__VisaMaster_mfl,
mttarjeta_master_debitos_automaticos__VisaMaster_mfl,
mttarjeta_visa_debitos_automaticos__VisaMaster_mfl
)

SELECT

numero_de_cliente,

CAST(mactivos_margen / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(marketing_coss_selling / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mautoservicio / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mbonos_corporativos / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcaja_ahorro_Nopaquete / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcaja_ahorro_Paquete / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcaja_ahorro_dolares / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcajeros_ajenos / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcajeros_propio / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcajeros_propios_descuentos / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcambio_monedas_compra / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcambio_monedas_venta / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcheques_depositados / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcheques_depositados_rechazados / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcheques_emitidos / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcheques_emitidos_rechazados / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcomisiones / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcomisiones_mantenimiento / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcomisiones_otras / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcuenta_corriente_Nopaquete / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcuenta_corriente_Paquete / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcuenta_corriente_dolares / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcuenta_debitos_automaticos / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcuenta_descuentos / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcuentas_saldo / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mdescubierto_preacordado / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mextraccion_autoservicio / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mfondos_comunes_inversion_dolares / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mfondos_comunes_inversion_pesos / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(minversiones_otras / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mmonedas_extranjeras / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mpagodeservicios / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mpagomiscuentas / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mpasivos_margen / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mprestamos_hipotecarios / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mprestamos_personales / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mprestamos_prendarios / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mrentabilidad / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mrentabilidad_annual / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mtarjeta_master_consumo / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mtarjeta_master_descuentos / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mtarjeta_visa_consumo / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mtarjeta_visa_descuentos / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mtitulos / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mtransferencias_emitidas / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mtransferencias_recibidas / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mttarjeta_master_debitos_automaticos / Master_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mttarjeta_visa_debitos_automaticos / Master_mfinanciacion_limite AS DECIMAL(7,5)),

CAST(mactivos_margen / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(marketing_coss_selling / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mautoservicio / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mbonos_corporativos / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcaja_ahorro_Nopaquete / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcaja_ahorro_Paquete / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcaja_ahorro_dolares / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcajeros_ajenos / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcajeros_propio / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcajeros_propios_descuentos / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcambio_monedas_compra / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcambio_monedas_venta / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcheques_depositados / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcheques_depositados_rechazados / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcheques_emitidos / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcheques_emitidos_rechazados / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcomisiones / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcomisiones_mantenimiento / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcomisiones_otras / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcuenta_corriente_Nopaquete / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcuenta_corriente_Paquete / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcuenta_corriente_dolares / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcuenta_debitos_automaticos / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcuenta_descuentos / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mcuentas_saldo / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mdescubierto_preacordado / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mextraccion_autoservicio / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mfondos_comunes_inversion_dolares / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mfondos_comunes_inversion_pesos / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(minversiones_otras / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mmonedas_extranjeras / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mpagodeservicios / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mpagomiscuentas / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mpasivos_margen / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mprestamos_hipotecarios / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mprestamos_personales / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mprestamos_prendarios / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mrentabilidad / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mrentabilidad_annual / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mtarjeta_master_consumo / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mtarjeta_master_descuentos / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mtarjeta_visa_consumo / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mtarjeta_visa_descuentos / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mtitulos / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mtransferencias_emitidas / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mtransferencias_recibidas / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mttarjeta_master_debitos_automaticos / Visa_mfinanciacion_limite AS DECIMAL(7,5)),
CAST(mttarjeta_visa_debitos_automaticos / Visa_mfinanciacion_limite AS DECIMAL(7,5)),

CAST(mactivos_margen / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(marketing_coss_selling / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mautoservicio / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mbonos_corporativos / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcaja_ahorro_Nopaquete / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcaja_ahorro_Paquete / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcaja_ahorro_dolares / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcajeros_ajenos / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcajeros_propio / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcajeros_propios_descuentos / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcambio_monedas_compra / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcambio_monedas_venta / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcheques_depositados / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcheques_depositados_rechazados / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcheques_emitidos / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcheques_emitidos_rechazados / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcomisiones / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcomisiones_mantenimiento / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcomisiones_otras / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcuenta_corriente_Nopaquete / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcuenta_corriente_Paquete / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcuenta_corriente_dolares / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcuenta_debitos_automaticos / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcuenta_descuentos / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mcuentas_saldo / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mdescubierto_preacordado / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mextraccion_autoservicio / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mfondos_comunes_inversion_dolares / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mfondos_comunes_inversion_pesos / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(minversiones_otras / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mmonedas_extranjeras / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mpagodeservicios / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mpagomiscuentas / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mpasivos_margen / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mprestamos_hipotecarios / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mprestamos_personales / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mprestamos_prendarios / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mrentabilidad / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mrentabilidad_annual / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mtarjeta_master_consumo / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mtarjeta_master_descuentos / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mtarjeta_visa_consumo / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mtarjeta_visa_descuentos / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mtitulos / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mtransferencias_emitidas / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mtransferencias_recibidas / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mttarjeta_master_debitos_automaticos / Master_mlimitecompra AS DECIMAL(7,5)),
CAST(mttarjeta_visa_debitos_automaticos / Master_mlimitecompra AS DECIMAL(7,5)),

CAST(mactivos_margen / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(marketing_coss_selling / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mautoservicio / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mbonos_corporativos / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcaja_ahorro_Nopaquete / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcaja_ahorro_Paquete / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcaja_ahorro_dolares / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcajeros_ajenos / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcajeros_propio / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcajeros_propios_descuentos / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcambio_monedas_compra / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcambio_monedas_venta / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcheques_depositados / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcheques_depositados_rechazados / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcheques_emitidos / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcheques_emitidos_rechazados / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcomisiones / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcomisiones_mantenimiento / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcomisiones_otras / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcuenta_corriente_Nopaquete / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcuenta_corriente_Paquete / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcuenta_corriente_dolares / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcuenta_debitos_automaticos / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcuenta_descuentos / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mcuentas_saldo / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mdescubierto_preacordado / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mextraccion_autoservicio / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mfondos_comunes_inversion_dolares / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mfondos_comunes_inversion_pesos / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(minversiones_otras / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mmonedas_extranjeras / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mpagodeservicios / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mpagomiscuentas / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mpasivos_margen / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mprestamos_hipotecarios / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mprestamos_personales / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mprestamos_prendarios / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mrentabilidad / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mrentabilidad_annual / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mtarjeta_master_consumo / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mtarjeta_master_descuentos / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mtarjeta_visa_consumo / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mtarjeta_visa_descuentos / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mtitulos / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mtransferencias_emitidas / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mtransferencias_recibidas / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mttarjeta_master_debitos_automaticos / Visa_mlimitecompra AS DECIMAL(7,5)),
CAST(mttarjeta_visa_debitos_automaticos / Visa_mlimitecompra AS DECIMAL(7,5)),

CAST(mactivos_margen / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(marketing_coss_selling / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mautoservicio / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mbonos_corporativos / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcaja_ahorro_Nopaquete / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcaja_ahorro_Paquete / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcaja_ahorro_dolares / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcajeros_ajenos / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcajeros_propio / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcajeros_propios_descuentos / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcambio_monedas_compra / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcambio_monedas_venta / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcheques_depositados / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcheques_depositados_rechazados / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcheques_emitidos / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcheques_emitidos_rechazados / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcomisiones / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcomisiones_mantenimiento / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcomisiones_otras / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcuenta_corriente_Nopaquete / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcuenta_corriente_Paquete / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcuenta_corriente_dolares / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcuenta_debitos_automaticos / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcuenta_descuentos / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mcuentas_saldo / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mdescubierto_preacordado / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mextraccion_autoservicio / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mfondos_comunes_inversion_dolares / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mfondos_comunes_inversion_pesos / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(minversiones_otras / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mmonedas_extranjeras / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mpagodeservicios / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mpagomiscuentas / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mpasivos_margen / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mprestamos_hipotecarios / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mprestamos_personales / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mprestamos_prendarios / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mrentabilidad / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mrentabilidad_annual / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mtarjeta_master_consumo / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mtarjeta_master_descuentos / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mtarjeta_visa_consumo / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mtarjeta_visa_descuentos / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mtitulos / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mtransferencias_emitidas / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mtransferencias_recibidas / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mttarjeta_master_debitos_automaticos / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5)),
CAST(mttarjeta_visa_debitos_automaticos / (Visa_mfinanciacion_limite + Master_mfinanciacion_limite) AS DECIMAL(7,5))

FROM hasta_abril
WHERE foto_mes = 201604
ORDER BY numero_de_cliente ASC;
